### ISSUE TITLE
 Ambiguous error in README.md

### ISSUE THREAD

**Issue by ghost** [Jachdich/planet-client#6]
"I may commit broken code because I cba making a new branch.", not exactly sure what is meant to be conveyed in this sentence.

**Comment by Jachdich** [comment]
Well, it means that there's no guarantee that the code will work since I'm usually working on it and I don't always finish making it work before I have to upload to GitHub

**Comment by ghost** [comment]
I mean the cba thing? Is that not a typo?

**Comment by Jachdich** [comment]
CBA == Can't Be Arsed/Assed
